CREATE TABLE `delivered_leads_tci` (
  `landing_page` varchar(250) DEFAULT NULL,
  `campaign` varchar(250) DEFAULT NULL,
  `first_name` varchar(250) DEFAULT NULL,
  `last_name` varchar(250) DEFAULT NULL,
  `title` varchar(250) DEFAULT NULL,
  `company` varchar(250) DEFAULT NULL,
  `email` varchar(250) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `street` varchar(250) DEFAULT NULL,
  `city` varchar(250) DEFAULT NULL,
  `state_province` varchar(250) DEFAULT NULL,
  `zip_postal_code` varchar(250) DEFAULT NULL,
  `company_Size` varchar(250) DEFAULT NULL,
  `country` varchar(250) DEFAULT NULL,
  `Industry` varchar(250) DEFAULT NULL,
  `region` varchar(250) DEFAULT NULL,
  `job_function` varchar(250) DEFAULT NULL,
  `title_category` varchar(250) DEFAULT NULL,
  `technology_interest` varchar(250) DEFAULT NULL,
  `technology_installed` varchar(250) DEFAULT NULL,
  `comments` varchar(250) DEFAULT NULL,
  `duns` varchar(250) DEFAULT NULL,
  `web_address` varchar(250) DEFAULT NULL,
  `revenue` varchar(250) DEFAULT NULL,
  `linkedin` varchar(250) DEFAULT NULL,
  `selected_docs` varchar(250) DEFAULT NULL,
  `client_name` varchar(250) DEFAULT NULL,
  `delivery_date` date DEFAULT NULL,
  `insert_dttm` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_dttm` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)